### PR TITLE
Added Indonesian translation

### PR DESCRIPTION
**Pull request by adam-adrian**

### CODE REVIEW

**Comment by rliwoch** [comment]
Thank you @adam-adrian 
There's a new version coming with a lot of changes (https://github.com/rliwoch/plasmoid-wunderground-extended/pull/6), and will require some additional lines to be translated. 

If you don't mind, I'd like to hold off until that is ready and I'd really appreciate if you could add those additional translations. Is it OK by you?

**Comment by adam-adrian** [comment]
OK, don't worry

**Comment by adam-adrian** [comment]
I Will waiting until it's ready

**Comment by rliwoch** [comment]
@adam-adrian Hi!
Can you please rebase on top of `develop`, update the translations and then direct this PR to `develop`? 
For context most of the new translations are coming from a new alternative weather details tab and the settings to configure the weather station
image

**Comment by adam-adrian** [comment]
How to Rebase? I'm new to GitHub.

**Comment by adam-adrian** [comment]
Can you tell me?

**Comment by adam-adrian** [comment]
Can i edit it directly from here?

**Comment by rliwoch** [comment]
@adam-adrian I was just doing it on this branch but I think you changed something the minute I did it :)
Hold on please - I'll create a new branch here that you should be able to see in your fork and edit there

**Comment by adam-adrian** [comment]
Ok, and by the way, i'm on android now (not in the 
mobile app, in browser).

**Comment by rliwoch** [comment]
generally speaking "rebasing" means "moving your commits on top of a different branch". The way you do it, is when you are on your branch X and you say "git rebase main" or "git rebase develop" then it will take changes from the branch X and apply them onto a new base (hence REbase - changing the base of your branch)

Here, please. I created a branch feature/indonesian - you should be able to fork it/edit it and then recreate the pull request:

https://github.com/rliwoch/plasmoid-wunderground-extended/blob/feature/indonesian/plasmoid/translate/id_ID.po

**Comment by adam-adrian** [comment]
Ok, i understand now

**Comment by rliwoch** [comment]
let me know if you have any issues. I'll help :) it's just the time difference makes it already a midnight here :)

**Comment by adam-adrian** [comment]
Ok, thank you so much for helping me.
And can you give me time? I cant use my  computer now. Maybe 4/5 hours

**Comment by rliwoch** [comment]
yes, of course - not a problem at all, I'm just collecting some other translations and will be retesting everything tomorrow. 

Take your time and thank you very much by helping with the translations!

**Comment by adam-adrian** [comment]
Thank you, i appreciate your hard work 😉
I Will offline now.

**Pull request closed without merging**
