### PR TITLE
Update Indonesian Translation

### PR DESCRIPTION
**Pull request by adam-adrian**
Done!
Screenshot_20220424_101509

### CODE REVIEW

**Comment by rliwoch** [comment]
Wonderful, thank you! Great job
I need to check why the response from the weather api is not translated on your screenshot, maybe they don't provide Indonesian.

BTW, please remember to update to the final version once it's released, there will be some additional new fixes there 😊

**Review by rliwoch — APPROVED** [review]
looks good, thank you

**Comment by adam-adrian** [comment]
Your welcome!

**Comment by rliwoch** [comment]
btw. all is good, Indonesian is provided by the weather API. There was one minor issue but I fixed it

image

**Comment by rliwoch** [comment]
and by the way I envy your weather so much right now ;) 
I've been to Indonesia a couple of times and absolutely loved it! Once again cheers for the translation.

**Comment by adam-adrian** [comment]
Also, can you make the wind direction translatable? maybe users will get confused about it

**Comment by rliwoch** [comment]
yes, but that's todo for the next version.

The problem is the weather station reports wind cardinal, as in degrees, for example 167 degrees, so at the minute it's a bit of a hack to convert degrees to human readable letters representing N/E/S/W etc. 

There's another API that returns localised wind direction I could use but that's a bit more involving change and I already have a massive changeset in this version

**Comment by adam-adrian** [comment]
Oh, OK

**Comment by adam-adrian** [comment]
@rliwoch , can you check the text "request to %1 couldn't be sent....." ? Looks like it's broken (flashing). I test it when offline, i changed the translation, but it's still flashing until i remove the %1 and %2 text, and it spammed the terminal log when i restart plasmashell.

**Comment by adam-adrian** [comment]
(oh maybe i have to write this in issue)

**Comment by rliwoch** [comment]
yes, please - create an issue for it with as much information as possible.

**Comment by adam-adrian** [comment]
Done! #13

**Comment by adam-adrian** [comment]
I Will complete the issue tomorrow

**Pull request merged**
